name: cartoonizer
description: Turn Photo to Cartoon Online Free - No Ads

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.6+305

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  simple_shadow: ^0.3.0
  dotted_border: 2.0.0+3
  image_picker: 0.8.6
  #  images_picker: 1.2.11
  http: ^0.13.4
  dio: ^4.0.6
  crypto: ^3.0.1
  loading_overlay: ^0.3.0
  pin_code_fields: ^7.3.0
  flutter_native_splash: ^2.1.5
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.12
  path: ^1.8.0
  path_provider: ^2.0.8
  gallery_saver: 2.3.2
  share_plus: 6.3.4
  url_launcher: 6.1.11
  flutter_share_me: 1.3.0
  get: ^4.6.3
  get_storage: ^2.0.3
  scrollable_positioned_list: ^0.3.7
  flutter_email_sender: ^5.0.2
  in_app_purchase: ^2.0.1
  firebase_core: 2.15.1
  firebase_auth: 4.8.0
  firebase_messaging: ^14.6.7
  cloud_firestore_web: 3.7.0
  flutter_facebook_auth: 4.1.0
  google_sign_in: ^5.2.3
  sign_in_with_apple: ^3.3.0
  video_player: ^2.2.18
  webview_flutter: ^3.0.0
  connectivity_plus: ^2.2.1
  permission_handler: 10.2.0
  cached_network_image: 3.1.0+1
  flutter_credit_card: 3.0.1
  package_info_plus: 3.0.3
  device_info_plus: 8.1.0
  app_tracking_transparency: ^2.0.3
  firebase_analytics: 10.4.5
  google_mobile_ads: 2.3.0
  flutter_staggered_grid_view: 0.6.2
  #    git:
  #      url: https://github.com/googleads/googleads-mobile-flutter
  #      path: packages/google_mobile_ads
  flutter_image_compress: 2.0.1
  flutter_local_notifications: 9.6.1
  common_utils: ^2.1.0
  flutter_easyrefresh: ^2.2.1
  waterfall_flow: 3.0.2
  photo_view: ^0.14.0
  event_bus: ^2.0.0
  flutter_svg: ^1.0.3
  firebase_crashlytics: ^3.3.5
  mmoo_forbidshot: 1.0.3
  flutter_switch: 0.3.2
  vibration: ^1.7.4-nullsafety.0
  google_mlkit_commons: 0.3.0
  google_mlkit_face_detection: 0.6.0
  photo_manager: 2.6.0
  # intl dependencies
  flutter_localizations:
    sdk: flutter
  custom_pop_up_menu: 1.2.4
  camera: 0.10.5
  image: 3.2.2
  sensors_plus: 2.0.5
  #  opencv_4: ^1.0.0
  ffmpeg_kit_flutter: 5.1.0
  posthog_flutter: 2.0.3
  uni_links: 0.5.1
  like_button: 2.0.5
  skeletons: 0.0.3
  socket_io_client: 1.0.2
  palette_generator: 0.3.3+2
  crop_your_image: 0.7.3
  kochava_tracker: 2.0.2
  flutter_google_places: 0.3.0
  calendar_date_picker2: 0.5.2
  #  croppy: 0.2.6
  card_swiper: 2.0.4
  flutter_swiper_null_safety: 1.0.2
  intl_phone_number_input: 0.7.3+1
  visibility_detector: 0.3.3
  tutorial_coach_mark: 1.2.9
  worker_manager: 5.0.3
  keframe: ^3.0.0
  flutter_image_filters: 0.0.15

  cassowary: ^0.4.2
  plugin_platform_interface: ^2.0.2
  ffi: ^2.0.2
  equatable: ^2.0.5
  vector_math: ^2.1.4
dependency_overrides:
  intl: 0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  gallery_saver: any
  firebase_core_platform_interface: 4.8.0
  ffigen: ^8.0.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal
    - family: BlackOpsOne
      fonts:
        - asset: assets/fonts/BlackOpsOne-Regular.ttf
          style: normal
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
