const calling_code_es = [
  {
    "regionName": "Isla de ascensión",
    "callingCode": "+247",
    "regionCode": "AC",
    "regionFlag": "🇦🇨",
  },
  {
    "regionCode": "AD",
    "regionFlag": "🇦🇩",
    "regionName": "andorrano",
    "callingCode": "+376",
  },
  {
    "regionCode": "AE",
    "callingCode": "+971",
    "regionFlag": "🇦🇪",
    "regionName": "Emiratos Árabes Unidos",
  },
  {
    "regionFlag": "🇦🇫",
    "regionCode": "AF",
    "callingCode": "+93",
    "regionName": "afgano",
  },
  {
    "regionCode": "AG",
    "regionName": "Antigua y barbuda",
    "callingCode": "+1-268",
    "regionFlag": "🇦🇬",
  },
  {
    "callingCode": "+1-264",
    "regionCode": "AI",
    "regionFlag": "🇦🇮",
    "regionName": "Isla de anguilla",
  },
  {
    "regionName": "albanés",
    "regionCode": "AL",
    "callingCode": "+355",
    "regionFlag": "🇦🇱",
  },
  {
    "regionCode": "AM",
    "regionFlag": "🇦🇲",
    "regionName": "armenio",
    "callingCode": "+374",
  },
  {
    "regionName": "angoleño",
    "regionCode": "AO",
    "callingCode": "+244",
    "regionFlag": "🇦🇴",
  },
  {
    "regionFlag": "🇦🇶",
    "regionName": "antártida",
    "callingCode": "+672",
    "regionCode": "AQ",
  },
  {
    "regionCode": "AR",
    "regionName": "argentino",
    "regionFlag": "🇦🇷",
    "callingCode": "+54",
  },
  {
    "callingCode": "+1-684",
    "regionName": "Samoa americana",
    "regionFlag": "🇦🇸",
    "regionCode": "AS",
  },
  {
    "regionCode": "AT",
    "regionFlag": "🇦🇹",
    "callingCode": "+43",
    "regionName": "Austria",
  },
  {
    "regionCode": "AU",
    "regionName": "australiano",
    "callingCode": "+61",
    "regionFlag": "🇦🇺",
  },
  {
    "callingCode": "+297",
    "regionName": "Aruba",
    "regionCode": "AW",
    "regionFlag": "🇦🇼",
  },
  {
    "regionName": "Islas aland",
    "regionFlag": "🇦🇽",
    "regionCode": "AX",
    "callingCode": "+358",
  },
  {
    "callingCode": "+994",
    "regionFlag": "🇦🇿",
    "regionName": "azerí",
    "regionCode": "AZ",
  },
  {
    "regionCode": "BA",
    "callingCode": "+387",
    "regionFlag": "🇧🇦",
    "regionName": "Bosnia y herzegovina",
  },
  {
    "regionCode": "BB",
    "regionFlag": "🇧🇧",
    "regionName": "barbado",
    "callingCode": "+1-246",
  },
  {
    "callingCode": "+880",
    "regionCode": "BD",
    "regionFlag": "🇧🇩",
    "regionName": "bangladés",
  },
  {
    "callingCode": "+32",
    "regionCode": "BE",
    "regionName": "belga",
    "regionFlag": "🇧🇪",
  },
  {
    "callingCode": "+226",
    "regionFlag": "🇧🇫",
    "regionName": "burkinés",
    "regionCode": "BF",
  },
  {
    "regionName": "búlgaro",
    "callingCode": "+359",
    "regionCode": "BG",
    "regionFlag": "🇧🇬",
  },
  {
    "regionName": "bahrein",
    "regionFlag": "🇧🇭",
    "callingCode": "+973",
    "regionCode": "BH",
  },
  {
    "regionFlag": "🇧🇮",
    "regionName": "burundés",
    "regionCode": "BI",
    "callingCode": "+257",
  },
  {
    "regionName": "Benín",
    "regionFlag": "🇧🇯",
    "regionCode": "BJ",
    "callingCode": "+229",
  },
  {
    "callingCode": "+590",
    "regionName": "Santo Bartolomé",
    "regionCode": "BL",
    "regionFlag": "🇧🇱",
  },
  {
    "regionName": "Bermudas",
    "callingCode": "+1-441",
    "regionCode": "BM",
    "regionFlag": "🇧🇲",
  },
  {
    "regionName": "Brunei",
    "regionCode": "BN",
    "regionFlag": "🇧🇳",
    "callingCode": "+673",
  },
  {
    "regionName": "boliviano",
    "callingCode": "+591",
    "regionCode": "BO",
    "regionFlag": "🇧🇴",
  },
  {
    "regionName": "Países Bajos Caribeños",
    "callingCode": "+599",
    "regionFlag": "🇧🇶",
    "regionCode": "BQ",
  },
  {
    "regionName": "Brasil",
    "regionCode": "BR",
    "callingCode": "+55",
    "regionFlag": "🇧🇷",
  },
  {
    "regionFlag": "🇧🇸",
    "regionCode": "BS",
    "regionName": "Bahamas",
    "callingCode": "+1-242",
  },
  {
    "regionCode": "BT",
    "regionName": "Bután",
    "callingCode": "+975",
    "regionFlag": "🇧🇹",
  },
  {
    "regionFlag": "🇧🇼",
    "regionName": "Botsuana",
    "regionCode": "BW",
    "callingCode": "+267",
  },
  {
    "regionCode": "BY",
    "regionFlag": "🇧🇾",
    "regionName": "Bielorrusia",
    "callingCode": "+375",
  },
  {
    "regionCode": "BZ",
    "regionFlag": "🇧🇿",
    "callingCode": "+501",
    "regionName": "Belice",
  },
  {
    "callingCode": "+1",
    "regionCode": "CA",
    "regionName": "Canadá",
    "regionFlag": "🇨🇦",
  },
  {
    "regionCode": "CC",
    "regionFlag": "🇨🇨",
    "regionName": "Islas Cocos (Keeling)",
    "callingCode": "+61",
  },
  {
    "callingCode": "+243",
    "regionCode": "CD",
    "regionFlag": "🇨🇩",
    "regionName": "República Democrática del Congo",
  },
  {
    "callingCode": "+236",
    "regionCode": "CF",
    "regionFlag": "🇨🇫",
    "regionName": "República Centroafricana",
  },
  {
    "callingCode": "+242",
    "regionName": "República del Congo",
    "regionCode": "CG",
    "regionFlag": "🇨🇬",
  },
  {
    "callingCode": "+41",
    "regionName": "Suiza",
    "regionFlag": "🇨🇭",
    "regionCode": "CH",
  },
  {
    "callingCode": "+225",
    "regionFlag": "🇨🇮",
    "regionCode": "CI",
    "regionName": "Costa de Marfil",
  },
  {
    "regionFlag": "🇨🇰",
    "regionCode": "CK",
    "regionName": "Islas Cook",
    "callingCode": "+682",
  },
  {
    "regionName": "Chile",
    "regionCode": "CL",
    "callingCode": "+56",
    "regionFlag": "🇨🇱",
  },
  {
    "callingCode": "+237",
    "regionFlag": "🇨🇲",
    "regionCode": "CM",
    "regionName": "Camerún",
  },
  {
    "regionFlag": "🇨🇳",
    "callingCode": "+86",
    "regionName": "China continental",
    "regionCode": "CN",
  },
  {
    "regionName": "Colombia",
    "regionFlag": "🇨🇴",
    "regionCode": "CO",
    "callingCode": "+57",
  },
  {
    "regionFlag": "🇨🇷",
    "callingCode": "+506",
    "regionName": "Costa Rica",
    "regionCode": "CR",
  },
  {
    "regionName": "Cuba",
    "regionFlag": "🇨🇺",
    "regionCode": "CU",
    "callingCode": "+53",
  },
  {
    "regionFlag": "🇨🇻",
    "regionName": "Cabo Verde",
    "callingCode": "+238",
    "regionCode": "CV",
  },
  {
    "regionFlag": "🇨🇼",
    "regionCode": "CW",
    "regionName": "Curazao",
    "callingCode": "+599 9",
  },
  {
    "regionCode": "CX",
    "regionName": "Isla de Navidad",
    "callingCode": "+61",
    "regionFlag": "🇨🇽",
  },
  {
    "regionName": "Chipre",
    "regionCode": "CY",
    "callingCode": "+357",
    "regionFlag": "🇨🇾",
  },
  {
    "callingCode": "+420",
    "regionFlag": "🇨🇿",
    "regionCode": "CZ",
    "regionName": "Chequia",
  },
  {
    "regionName": "Alemania",
    "regionFlag": "🇩🇪",
    "regionCode": "DE",
    "callingCode": "+49",
  },
  {
    "regionCode": "DJ",
    "callingCode": "+253",
    "regionName": "Yibuti",
    "regionFlag": "🇩🇯",
  },
  {
    "regionFlag": "🇩🇰",
    "regionCode": "DK",
    "regionName": "Dinamarca",
    "callingCode": "+45",
  },
  {
    "callingCode": "+1-767",
    "regionFlag": "🇩🇲",
    "regionName": "Dominica",
    "regionCode": "DM",
  },
  {
    "regionFlag": "🇩🇴",
    "regionCode": "DO",
    "regionName": "República Dominicana",
    "callingCode": "+1-849",
  },
  {
    "regionCode": "DZ",
    "regionFlag": "🇩🇿",
    "callingCode": "+213",
    "regionName": "Argelia",
  },
  {
    "regionCode": "EC",
    "regionName": "Ecuador",
    "callingCode": "+593",
    "regionFlag": "🇪🇨",
  },
  {
    "callingCode": "+372",
    "regionName": "Estonia",
    "regionCode": "EE",
    "regionFlag": "🇪🇪",
  },
  {
    "regionFlag": "🇪🇬",
    "regionCode": "EG",
    "regionName": "Egipto",
    "callingCode": "+20",
  },
  {
    "regionName": "Sahara Occidental",
    "regionFlag": "🇪🇭",
    "regionCode": "EH",
    "callingCode": "+212",
  },
  {
    "regionCode": "ER",
    "regionFlag": "🇪🇷",
    "callingCode": "+291",
    "regionName": "Eritrea",
  },
  {
    "regionFlag": "🇪🇸",
    "callingCode": "+34",
    "regionCode": "ES",
    "regionName": "España",
  },
  {
    "callingCode": "+251",
    "regionFlag": "🇪🇹",
    "regionCode": "ET",
    "regionName": "Etiopía",
  },
  {
    "regionFlag": "🇫🇮",
    "regionCode": "FI",
    "callingCode": "+358",
    "regionName": "Finlandia",
  },
  {
    "regionCode": "FJ",
    "regionFlag": "🇫🇯",
    "regionName": "Fiyi",
    "callingCode": "+679",
  },
  {
    "regionName": "Islas Malvinas",
    "regionCode": "FK",
    "regionFlag": "🇫🇰",
    "callingCode": "+500",
  },
  {
    "regionFlag": "🇫🇲",
    "regionName": "Micronesia",
    "callingCode": "+691",
    "regionCode": "FM",
  },
  {
    "regionCode": "FO",
    "regionName": "Islas Feroe",
    "regionFlag": "🇫🇴",
    "callingCode": "+298",
  },
  {
    "regionCode": "FR",
    "regionFlag": "🇫🇷",
    "regionName": "Francia",
    "callingCode": "+33",
  },
  {
    "regionFlag": "🇬🇦",
    "callingCode": "+241",
    "regionName": "Gabón",
    "regionCode": "GA",
  },
  {
    "callingCode": "+44",
    "regionFlag": "🇬🇧",
    "regionCode": "GB",
    "regionName": "Reino Unido",
  },
  {
    "regionCode": "GD",
    "regionName": "Granada",
    "callingCode": "+1-473",
    "regionFlag": "🇬🇩",
  },
  {
    "regionCode": "GE",
    "regionFlag": "🇬🇪",
    "callingCode": "+995",
    "regionName": "Georgia",
  },
  {
    "regionName": "Guayana Francesa",
    "regionFlag": "🇬🇫",
    "callingCode": "+594",
    "regionCode": "GF",
  },
  {
    "callingCode": "+44",
    "regionName": "Guernsey",
    "regionCode": "GG",
    "regionFlag": "🇬🇬",
  },
  {
    "callingCode": "+233",
    "regionFlag": "🇬🇭",
    "regionCode": "GH",
    "regionName": "Ghana",
  },
  {
    "regionName": "Gibraltar",
    "regionCode": "GI",
    "regionFlag": "🇬🇮",
    "callingCode": "+350",
  },
  {
    "regionFlag": "🇬🇱",
    "regionCode": "GL",
    "regionName": "Groenlandia",
    "callingCode": "+299",
  },
  {
    "regionCode": "GM",
    "callingCode": "+220",
    "regionFlag": "🇬🇲",
    "regionName": "Gambia",
  },
  {
    "regionName": "Guinea",
    "regionFlag": "🇬🇳",
    "regionCode": "GN",
    "callingCode": "+224",
  },
  {
    "callingCode": "+590",
    "regionCode": "GP",
    "regionFlag": "🇬🇵",
    "regionName": "Guadalupe",
  },
  {
    "regionCode": "GQ",
    "regionFlag": "🇬🇶",
    "callingCode": "+240",
    "regionName": "Guinea Ecuatorial",
  },
  {
    "callingCode": "+30",
    "regionCode": "GR",
    "regionFlag": "🇬🇷",
    "regionName": "Grecia",
  },
  {
    "regionFlag": "🇬🇸",
    "regionName": "Islas Georgias del Sur y Sandwich del Sur",
    "regionCode": "GS",
    "callingCode": "+500",
  },
  {
    "regionCode": "GT",
    "regionFlag": "🇬🇹",
    "callingCode": "+502",
    "regionName": "Guatemala",
  },
  {
    "regionCode": "GU",
    "callingCode": "+1-671",
    "regionName": "Guam",
    "regionFlag": "🇬🇺",
  },
  {
    "regionCode": "GW",
    "regionName": "Guinea-Bisáu",
    "callingCode": "+245",
    "regionFlag": "🇬🇼",
  },
  {
    "callingCode": "+595",
    "regionName": "Guyana",
    "regionCode": "GY",
    "regionFlag": "🇬🇾",
  },
  {
    "regionCode": "HK",
    "regionName": "Hong Kong, China",
    "regionFlag": "🇭🇰",
    "callingCode": "+852",
  },
  {
    "callingCode": "+672",
    "regionFlag": "🇭🇲",
    "regionName": "Islas Heard y McDonald",
    "regionCode": "HM",
  },
  {
    "regionCode": "HN",
    "callingCode": "+504",
    "regionName": "Honduras",
    "regionFlag": "🇭🇳",
  },
  {
    "regionCode": "HR",
    "regionFlag": "🇭🇷",
    "regionName": "Croacia",
    "callingCode": "+385",
  },
  {
    "regionFlag": "🇭🇹",
    "regionCode": "HT",
    "regionName": "Haití",
    "callingCode": "+509",
  },
  {
    "regionCode": "HU",
    "regionName": "Hungría",
    "regionFlag": "🇭🇺",
    "callingCode": "+36",
  },
  {
    "regionCode": "ID",
    "regionFlag": "🇮🇩",
    "callingCode": "+62",
    "regionName": "Indonesia",
  },
  {
    "callingCode": "+353",
    "regionName": "Irlanda",
    "regionCode": "IE",
    "regionFlag": "🇮🇪",
  },
  {
    "regionName": "Israel",
    "regionFlag": "🇮🇱",
    "callingCode": "+972",
    "regionCode": "IL",
  },
  {
    "regionCode": "IM",
    "callingCode": "+44",
    "regionFlag": "🇮🇲",
    "regionName": "Isla de Man",
  },
  {
    "regionCode": "IN",
    "regionFlag": "🇮🇳",
    "regionName": "India",
    "callingCode": "+91",
  },
  {
    "regionFlag": "🇮🇴",
    "regionCode": "IO",
    "callingCode": "+246",
    "regionName": "Territorio Británico del Océano Índico",
  },
  {
    "callingCode": "+964",
    "regionCode": "IQ",
    "regionFlag": "🇮🇶",
    "regionName": "Irak",
  },
  {
    "regionFlag": "🇮🇷",
    "callingCode": "+98",
    "regionCode": "IR",
    "regionName": "Irán",
  },
  {
    "regionCode": "IS",
    "regionFlag": "🇮🇸",
    "regionName": "Islandia",
    "callingCode": "+354",
  },
  {
    "regionName": "Italia",
    "callingCode": "+39",
    "regionCode": "IT",
    "regionFlag": "🇮🇹",
  },
  {
    "regionName": "Jersey",
    "regionCode": "JE",
    "regionFlag": "🇯🇪",
    "callingCode": "+44",
  },
  {
    "callingCode": "+1-876",
    "regionFlag": "🇯🇲",
    "regionCode": "JM",
    "regionName": "Jamaica",
  },
  {
    "regionName": "Jordania",
    "regionFlag": "🇯🇴",
    "regionCode": "JO",
    "callingCode": "+962",
  },
  {
    "regionCode": "JP",
    "callingCode": "+81",
    "regionFlag": "🇯🇵",
    "regionName": "Japón",
  },
  {
    "callingCode": "+254",
    "regionFlag": "🇰🇪",
    "regionName": "Kenia",
    "regionCode": "KE",
  },
  {
    "callingCode": "+996",
    "regionFlag": "🇰🇬",
    "regionName": "Kirguistán",
    "regionCode": "KG",
  },
  {
    "regionFlag": "🇰🇭",
    "regionCode": "KH",
    "callingCode": "+855",
    "regionName": "Camboya",
  },
  {
    "regionCode": "KI",
    "regionName": "Kiribati",
    "callingCode": "+686",
    "regionFlag": "🇰🇮",
  },
  {
    "regionName": "Comoras",
    "callingCode": "+269",
    "regionFlag": "🇰🇲",
    "regionCode": "KM",
  },
  {
    "regionFlag": "🇰🇳",
    "callingCode": "+1-869",
    "regionCode": "KN",
    "regionName": "San Cristóbal y Nieves",
  },
  {
    "regionCode": "KP",
    "regionFlag": "🇰🇵",
    "callingCode": "+850",
    "regionName": "Corea del Norte",
  },
  {
    "regionFlag": "🇰🇷",
    "callingCode": "+82",
    "regionName": "Corea del Sur",
    "regionCode": "KR",
  },
  {
    "callingCode": "+965",
    "regionCode": "KW",
    "regionFlag": "🇰🇼",
    "regionName": "Kuwait",
  },
  {
    "callingCode": "+345",
    "regionFlag": "🇰🇾",
    "regionCode": "KY",
    "regionName": "Islas Caimán",
  },
  {
    "regionFlag": "🇰🇿",
    "callingCode": "+7",
    "regionName": "Kazajistán",
    "regionCode": "KZ",
  },
  {
    "regionName": "Laos",
    "callingCode": "+856",
    "regionCode": "LA",
    "regionFlag": "🇱🇦",
  },
  {
    "regionName": "Líbano",
    "callingCode": "+961",
    "regionFlag": "🇱🇧",
    "regionCode": "LB",
  },
  {
    "regionFlag": "🇱🇨",
    "regionName": "Santa Lucía",
    "callingCode": "+1-758",
    "regionCode": "LC",
  },
  {
    "regionFlag": "🇱🇮",
    "regionName": "Liechtenstein",
    "regionCode": "LI",
    "callingCode": "+423",
  },
  {
    "regionFlag": "🇱🇰",
    "callingCode": "+94",
    "regionCode": "LK",
    "regionName": "Sri Lanka",
  },
  {
    "regionName": "Liberia",
    "regionCode": "LR",
    "regionFlag": "🇱🇷",
    "callingCode": "+231",
  },
  {
    "regionName": "Lesoto",
    "regionFlag": "🇱🇸",
    "callingCode": "+266",
    "regionCode": "LS",
  },
  {
    "regionName": "Lituania",
    "regionCode": "LT",
    "callingCode": "+370",
    "regionFlag": "🇱🇹",
  },
  {
    "callingCode": "+352",
    "regionFlag": "🇱🇺",
    "regionName": "Luxemburgo",
    "regionCode": "LU",
  },
  {
    "regionName": "Letonia",
    "regionFlag": "🇱🇻",
    "callingCode": "+371",
    "regionCode": "LV",
  },
  {
    "callingCode": "+218",
    "regionFlag": "🇱🇾",
    "regionCode": "LY",
    "regionName": "Libia",
  },
  {
    "regionCode": "MA",
    "regionName": "Marruecos",
    "regionFlag": "🇲🇦",
    "callingCode": "+212",
  },
  {
    "regionFlag": "🇲🇨",
    "callingCode": "+377",
    "regionName": "Mónaco",
    "regionCode": "MC",
  },
  {
    "regionFlag": "🇲🇩",
    "regionCode": "MD",
    "regionName": "Moldavia",
    "callingCode": "+373",
  },
  {
    "regionCode": "ME",
    "regionName": "Montenegro",
    "regionFlag": "🇲🇪",
    "callingCode": "+382",
  },
  {
    "regionCode": "MF",
    "regionFlag": "🇲🇫",
    "regionName": "San Martín",
    "callingCode": "+590",
  },
  {
    "regionName": "Madagascar",
    "regionFlag": "🇲🇬",
    "regionCode": "MG",
    "callingCode": "+261",
  },
  {
    "regionName": "Islas Marshall",
    "regionCode": "MH",
    "regionFlag": "🇲🇭",
    "callingCode": "+692",
  },
  {
    "regionCode": "MK",
    "callingCode": "+389",
    "regionName": "Macedonia del Norte",
    "regionFlag": "🇲🇰",
  },
  {
    "callingCode": "+223",
    "regionCode": "ML",
    "regionFlag": "🇲🇱",
    "regionName": "Malí",
  },
  {
    "regionCode": "MM",
    "regionName": "Myanmar",
    "callingCode": "+95",
    "regionFlag": "🇲🇲",
  },
  {
    "regionFlag": "🇲🇳",
    "callingCode": "+976",
    "regionName": "Mongolia",
    "regionCode": "MN",
  },
  {
    "regionFlag": "🇲🇴",
    "regionCode": "MO",
    "callingCode": "+853",
    "regionName": "China Macau",
  },
  {
    "regionName": "Islas Marianas del Norte",
    "regionCode": "MP",
    "regionFlag": "🇲🇵",
    "callingCode": "+1-670",
  },
  {
    "regionFlag": "🇲🇶",
    "regionName": "Martinica",
    "callingCode": "+596",
    "regionCode": "MQ",
  },
  {
    "regionFlag": "🇲🇷",
    "callingCode": "+222",
    "regionCode": "MR",
    "regionName": "Mauritania",
  },
  {
    "regionName": "Montserrat",
    "regionCode": "MS",
    "regionFlag": "🇲🇸",
    "callingCode": "+1-664",
  },
  {
    "regionFlag": "🇲🇹",
    "regionName": "Malta",
    "regionCode": "MT",
    "callingCode": "+356",
  },
  {
    "regionName": "Mauricio",
    "regionFlag": "🇲🇺",
    "callingCode": "+230",
    "regionCode": "MU",
  },
  {
    "regionName": "Maldivas",
    "callingCode": "+960",
    "regionCode": "MV",
    "regionFlag": "🇲🇻",
  },
  {
    "callingCode": "+265",
    "regionFlag": "🇲🇼",
    "regionCode": "MW",
    "regionName": "Malawi",
  },
  {
    "regionFlag": "🇲🇽",
    "regionCode": "MX",
    "regionName": "México",
    "callingCode": "+52",
  },
  {
    "regionName": "Malasia",
    "callingCode": "+60",
    "regionCode": "MY",
    "regionFlag": "🇲🇾",
  },
  {
    "regionCode": "MZ",
    "regionFlag": "🇲🇿",
    "callingCode": "+258",
    "regionName": "Mozambique",
  },
  {
    "regionFlag": "🇳🇦",
    "regionName": "Namibia",
    "callingCode": "+264",
    "regionCode": "NA",
  },
  {
    "regionName": "Nueva Caledonia",
    "regionCode": "NC",
    "callingCode": "+687",
    "regionFlag": "🇳🇨",
  },
  {
    "callingCode": "+227",
    "regionName": "Níger",
    "regionFlag": "🇳🇪",
    "regionCode": "NE",
  },
  {
    "regionFlag": "🇳🇫",
    "regionName": "Isla Norfolk",
    "callingCode": "+672",
    "regionCode": "NF",
  },
  {
    "regionFlag": "🇳🇬",
    "regionName": "Nigeria",
    "regionCode": "NG",
    "callingCode": "+234",
  },
  {
    "regionName": "Nicaragua",
    "callingCode": "+505",
    "regionCode": "NI",
    "regionFlag": "🇳🇮",
  },
  {
    "regionFlag": "🇳🇱",
    "regionCode": "NL",
    "regionName": "Países Bajos",
    "callingCode": "+31",
  },
  {
    "callingCode": "+47",
    "regionCode": "NO",
    "regionFlag": "🇳🇴",
    "regionName": "Noruega",
  },
  {
    "regionFlag": "🇳🇵",
    "regionName": "Nepal",
    "callingCode": "+977",
    "regionCode": "NP",
  },
  {
    "regionFlag": "🇳🇷",
    "regionCode": "NR",
    "regionName": "Nauru",
    "callingCode": "+674",
  },
  {
    "regionCode": "NU",
    "regionName": "Niue",
    "regionFlag": "🇳🇺",
    "callingCode": "+683",
  },
  {
    "regionCode": "NZ",
    "regionFlag": "🇳🇿",
    "regionName": "Nueva Zelanda",
    "callingCode": "+64",
  },
  {
    "callingCode": "+968",
    "regionFlag": "🇴🇲",
    "regionName": "Omán",
    "regionCode": "OM",
  },
  {
    "callingCode": "+507",
    "regionName": "Panamá",
    "regionFlag": "🇵🇦",
    "regionCode": "PA",
  },
  {
    "regionCode": "PE",
    "regionName": "Perú",
    "callingCode": "+51",
    "regionFlag": "🇵🇪",
  },
  {
    "callingCode": "+689",
    "regionFlag": "🇵🇫",
    "regionName": "Polinesia Francesa",
    "regionCode": "PF",
  },
  {
    "regionCode": "PG",
    "regionFlag": "🇵🇬",
    "regionName": "Papúa Nueva Guinea",
    "callingCode": "+675",
  },
  {
    "regionName": "Filipinas",
    "regionFlag": "🇵🇭",
    "callingCode": "+63",
    "regionCode": "PH",
  },
  {
    "callingCode": "+92",
    "regionCode": "PK",
    "regionFlag": "🇵🇰",
    "regionName": "Pakistán",
  },
  {
    "regionCode": "PL",
    "regionFlag": "🇵🇱",
    "callingCode": "+48",
    "regionName": "Polonia",
  },
  {
    "regionName": "San Pedro y Miquelón",
    "regionFlag": "🇵🇲",
    "regionCode": "PM",
    "callingCode": "+508",
  },
  {
    "regionName": "Islas Pitcairn",
    "callingCode": "+872",
    "regionCode": "PN",
    "regionFlag": "🇵🇳",
  },
  {
    "regionName": "Puerto Rico",
    "regionCode": "PR",
    "regionFlag": "🇵🇷",
    "callingCode": "+1-939",
  },
  {
    "callingCode": "+970",
    "regionCode": "PS",
    "regionFlag": "🇵🇸",
    "regionName": "Territorios Palestinos",
  },
  {
    "regionCode": "PT",
    "regionFlag": "🇵🇹",
    "callingCode": "+351",
    "regionName": "Portugal",
  },
  {
    "regionName": "Palau",
    "callingCode": "+680",
    "regionFlag": "🇵🇼",
    "regionCode": "PW",
  },
  {
    "regionName": "Paraguay",
    "regionFlag": "🇵🇾",
    "callingCode": "+595",
    "regionCode": "PY",
  },
  {
    "regionCode": "QA",
    "regionName": "Catar",
    "regionFlag": "🇶🇦",
    "callingCode": "+974",
  },
  {
    "regionFlag": "🇷🇪",
    "regionName": "Reunión",
    "regionCode": "RE",
    "callingCode": "+262",
  },
  {
    "callingCode": "+40",
    "regionFlag": "🇷🇴",
    "regionName": "Rumania",
    "regionCode": "RO",
  },
  {
    "regionName": "Serbia",
    "regionCode": "RS",
    "regionFlag": "🇷🇸",
    "callingCode": "+381",
  },
  {
    "regionFlag": "🇷🇺",
    "regionName": "Rusia",
    "callingCode": "+7",
    "regionCode": "RU",
  },
  {
    "regionFlag": "🇷🇼",
    "regionName": "Ruanda",
    "callingCode": "+250",
    "regionCode": "RW",
  },
  {
    "regionName": "Arabia Saudita",
    "regionCode": "SA",
    "regionFlag": "🇸🇦",
    "callingCode": "+966",
  },
  {
    "regionCode": "SB",
    "regionName": "Islas Salomón",
    "callingCode": "+677",
    "regionFlag": "🇸🇧",
  },
  {
    "regionCode": "SC",
    "regionFlag": "🇸🇨",
    "callingCode": "+248",
    "regionName": "Seychelles",
  },
  {
    "regionCode": "SD",
    "regionName": "Sudán",
    "regionFlag": "🇸🇩",
    "callingCode": "+249",
  },
  {
    "regionName": "Suecia",
    "regionFlag": "🇸🇪",
    "callingCode": "+46",
    "regionCode": "SE",
  },
  {
    "callingCode": "+65",
    "regionFlag": "🇸🇬",
    "regionName": "Singapur",
    "regionCode": "SG",
  },
  {
    "regionFlag": "🇸🇭",
    "callingCode": "+290",
    "regionCode": "SH",
    "regionName": "Santa Elena",
  },
  {
    "regionName": "Eslovenia",
    "regionFlag": "🇸🇮",
    "regionCode": "SI",
    "callingCode": "+386",
  },
  {
    "callingCode": "+47",
    "regionName": "Svalbard y Jan Mayen",
    "regionCode": "SJ",
    "regionFlag": "🇸🇯",
  },
  {
    "regionCode": "SK",
    "regionName": "Eslovaquia",
    "callingCode": "+421",
    "regionFlag": "🇸🇰",
  },
  {
    "callingCode": "+232",
    "regionFlag": "🇸🇱",
    "regionCode": "SL",
    "regionName": "Sierra Leona",
  },
  {
    "regionCode": "SM",
    "regionFlag": "🇸🇲",
    "callingCode": "+378",
    "regionName": "San Marino",
  },
  {
    "callingCode": "+221",
    "regionCode": "SN",
    "regionName": "Senegal",
    "regionFlag": "🇸🇳",
  },
  {
    "regionCode": "SO",
    "regionName": "Somalia",
    "regionFlag": "🇸🇴",
    "callingCode": "+252",
  },
  {
    "regionFlag": "🇸🇷",
    "regionName": "Surinam",
    "callingCode": "+597",
    "regionCode": "SR",
  },
  {
    "regionFlag": "🇸🇸",
    "callingCode": "+211",
    "regionCode": "SS",
    "regionName": "Sudán del Sur",
  },
  {
    "regionName": "Santo Tomé y Príncipe",
    "callingCode": "+239",
    "regionCode": "ST",
    "regionFlag": "🇸🇹",
  },
  {
    "callingCode": "+503",
    "regionFlag": "🇸🇻",
    "regionCode": "SV",
    "regionName": "El Salvador",
  },
  {
    "regionFlag": "🇸🇽",
    "regionName": "Sint Maarten",
    "callingCode": "+1-721",
    "regionCode": "SX",
  },
  {
    "regionCode": "SY",
    "regionFlag": "🇸🇾",
    "regionName": "Siria",
    "callingCode": "+963",
  },
  {
    "regionCode": "SZ",
    "regionName": "Eswatini",
    "regionFlag": "🇸🇿",
    "callingCode": "+268",
  },
  {
    "regionFlag": "🇹🇦",
    "regionName": "Tristán de Acuña",
    "regionCode": "TA",
    "callingCode": "+290",
  },
  {
    "callingCode": "+1-649",
    "regionFlag": "🇹🇨",
    "regionCode": "TC",
    "regionName": "Islas Turcas y Caicos",
  },
  {
    "regionName": "Chad",
    "regionFlag": "🇹🇩",
    "callingCode": "+235",
    "regionCode": "TD",
  },
  {
    "regionCode": "TG",
    "regionFlag": "🇹🇬",
    "callingCode": "+228",
    "regionName": "Togo",
  },
  {
    "callingCode": "+66",
    "regionCode": "TH",
    "regionFlag": "🇹🇭",
    "regionName": "Tailandia",
  },
  {
    "regionName": "Tayikistán",
    "regionCode": "TJ",
    "callingCode": "+992",
    "regionFlag": "🇹🇯",
  },
  {
    "regionFlag": "🇹🇰",
    "regionName": "Tokelau",
    "regionCode": "TK",
    "callingCode": "+690",
  },
  {
    "regionCode": "TL",
    "regionName": "Timor Oriental",
    "callingCode": "+670",
    "regionFlag": "🇹🇱",
  },
  {
    "regionFlag": "🇹🇲",
    "regionName": "Turkmenistán",
    "callingCode": "+993",
    "regionCode": "TM",
  },
  {
    "regionFlag": "🇹🇳",
    "callingCode": "+216",
    "regionCode": "TN",
    "regionName": "Túnez",
  },
  {
    "callingCode": "+676",
    "regionFlag": "🇹🇴",
    "regionCode": "TO",
    "regionName": "Tonga",
  },
  {
    "regionName": "Turquía",
    "regionCode": "TR",
    "regionFlag": "🇹🇷",
    "callingCode": "+90",
  },
  {
    "callingCode": "+1-868",
    "regionCode": "TT",
    "regionName": "Trinidad y Tobago",
    "regionFlag": "🇹🇹",
  },
  {
    "regionName": "Tuvalu",
    "regionCode": "TV",
    "callingCode": "+688",
    "regionFlag": "🇹🇻",
  },
  {
    "regionCode": "TW",
    "regionName": "Chinese Taiwán",
    "regionFlag": "🇨🇳",
    "callingCode": "+886",
  },
  {
    "regionName": "Tanzania",
    "callingCode": "+255",
    "regionCode": "TZ",
    "regionFlag": "🇹🇿",
  },
  {
    "regionName": "Ucrania",
    "callingCode": "+380",
    "regionCode": "UA",
    "regionFlag": "🇺🇦",
  },
  {
    "regionFlag": "🇺🇬",
    "regionCode": "UG",
    "callingCode": "+256",
    "regionName": "Uganda",
  },
  {
    "callingCode": "+1",
    "regionFlag": "🇺🇸",
    "regionCode": "UM",
    "regionName": "Islas Ultramarinas Menores de EE. UU.",
  },
  {
    "callingCode": "+1",
    "regionName": "Estados Unidos",
    "regionFlag": "🇺🇸",
    "regionCode": "US",
  },
  {
    "regionFlag": "🇺🇾",
    "regionCode": "UY",
    "regionName": "Uruguay",
    "callingCode": "+598",
  },
  {
    "regionName": "Uzbekistán",
    "callingCode": "+998",
    "regionFlag": "🇺🇿",
    "regionCode": "UZ",
  },
  {
    "regionFlag": "🇻🇦",
    "regionName": "Ciudad del Vaticano",
    "callingCode": "+379",
    "regionCode": "VA",
  },
  {
    "regionCode": "VC",
    "regionName": "San Vicente y las Granadinas",
    "callingCode": "+1-784",
    "regionFlag": "🇻🇨",
  },
  {
    "regionFlag": "🇻🇪",
    "regionCode": "VE",
    "regionName": "Venezuela",
    "callingCode": "+58",
  },
  {
    "callingCode": "+1-284",
    "regionName": "Islas Vírgenes Británicas",
    "regionCode": "VG",
    "regionFlag": "🇻🇬",
  },
  {
    "regionCode": "VI",
    "regionFlag": "🇻🇮",
    "regionName": "Islas Vírgenes de EE. UU.",
    "callingCode": "+1-340",
  },
  {
    "callingCode": "+84",
    "regionName": "Vietnam",
    "regionCode": "VN",
    "regionFlag": "🇻🇳",
  },
  {
    "callingCode": "+678",
    "regionName": "Vanuatu",
    "regionFlag": "🇻🇺",
    "regionCode": "VU",
  },
  {
    "callingCode": "+681",
    "regionFlag": "🇼🇫",
    "regionCode": "WF",
    "regionName": "Wallis y Futuna",
  },
  {
    "regionCode": "WS",
    "regionName": "Samoa",
    "regionFlag": "🇼🇸",
    "callingCode": "+685",
  },
  {
    "regionFlag": "🇽🇰",
    "regionCode": "XK",
    "regionName": "Kosovo",
    "callingCode": "+383",
  },
  {
    "regionName": "Yemen",
    "regionCode": "YE",
    "callingCode": "+967",
    "regionFlag": "🇾🇪",
  },
  {
    "callingCode": "+262",
    "regionName": "Mayotte",
    "regionCode": "YT",
    "regionFlag": "🇾🇹",
  },
  {
    "regionCode": "ZA",
    "regionFlag": "🇿🇦",
    "regionName": "Sudáfrica",
    "callingCode": "+27",
  },
  {
    "callingCode": "+260",
    "regionFlag": "🇿🇲",
    "regionCode": "ZM",
    "regionName": "Zambia",
  },
  {"regionName": "Zimbabue", "regionCode": "ZW", "regionFlag": "🇿🇼", "callingCode": "+263"}
];
