// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyB0tbdNkAjG-WmJftW0OTXcbsGlUshVLCQ',
  //   appId: '1:869538790374:web:874bd9f3046ebc68fcf427',
  //   messagingSenderId: '869538790374',
  //   projectId: 'cartoonizer-11584',
  //   authDomain: 'cartoonizer-11584.firebaseapp.com',
  //   storageBucket: 'cartoonizer-11584.appspot.com',
  //   measurementId: 'G-Z7Z7FSV44M',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB01usFl2-r6GlzE_CdymQkNA6_YN_y9io',
    appId: '1:761058819999:android:752125b532f9a9ea5407aa',
    messagingSenderId: '761058819999',
    projectId: 'fair-terminus-266600',
    storageBucket: 'fair-terminus-266600.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6clMfdKAphkQ5Qu1Hr3JYDFu2N0WEKoY',
    appId: '1:761058819999:ios:a6e06dc89268600f5407aa',
    messagingSenderId: '761058819999',
    projectId: 'fair-terminus-266600',
    storageBucket: 'fair-terminus-266600.appspot.com',
    iosClientId: '761058819999-n5pl08h9hu8nda1ass58n789sl6quhe0.apps.googleusercontent.com',
    iosBundleId: 'io.socialbook.cartoonizer',
  );
}
