// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyB0tbdNkAjG-WmJftW0OTXcbsGlUshVLCQ',
  //   appId: '1:869538790374:web:874bd9f3046ebc68fcf427',
  //   messagingSenderId: '869538790374',
  //   projectId: 'cartoonizer-11584',
  //   authDomain: 'cartoonizer-11584.firebaseapp.com',
  //   storageBucket: 'cartoonizer-11584.appspot.com',
  //   measurementId: 'G-Z7Z7FSV44M',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYXngmO0G7RshkxWtLMPDW3avStoZSrTc',
    appId: '1:604569513046:android:50fe35dedefcd3c00b9ff7',
    messagingSenderId: '604569513046',
    projectId: 'socialbook-80193',
    storageBucket: 'socialbook-80193.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcIqGLgVY7YyKv4-tp1W0lJ-EPyOg_HeE',
    appId: '1:604569513046:ios:feefaf1e893c3ab00b9ff7',
    messagingSenderId: '604569513046',
    projectId: 'socialbook-80193',
    storageBucket: 'socialbook-80193.appspot.com',
    iosClientId: '604569513046-o5rthd4hqbjrpmb05gu2j49qc7i97erf.apps.googleusercontent.com',
    iosBundleId: 'io.socialbook.cartoonizer',
  );
}
